name: continuous_bottom_sheet
description: "A highly customizable Flutter package for creating a modal bottom sheet with multiple, swipeable pages."

homepage: https://github.com/Ehsan-abaci
repository: https://github.com/Ehsan-abaci/continuous_bottom_sheet.git

version: 2.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
